### ISSUE TITLE
Make the parser of EqEx format

### ISSUE THREAD

**Issue by Nircek** [Pikne-Programy/pikne-zadania#4]
@Marwyk2003, there is stuff to be done:
- [x] add the short space between a value and a unit in LaTeX form
- [x] add the possibility to redefine variable; currently, it throws an error like:
```
TypeError: this.variables[name].rand is not a function
    at EquationExercise.render (equationExercise.ts:331:53)
    at exercisesController.ts:162:36
    at Function.exists (exercisesController.ts:143:13)
    at exercisesController.ts:158:35
    at Function.predictDeath (exercisesController.ts:128:13)
    at ExercisesController.get (exercisesController.ts:156:31)
    at dispatch (middleware.ts:41:13)
    at seed (seedMiddleware.ts:14:9)
    at dispatch (middleware.ts:41:13)
    at router.ts:866:20
 ```
- [x] ignore the spaces in the calculation part
- [x] add a possibility to have `'` in a variable name and compile it nicely to LaTeX
- [x] add the static property in EqEx specifies a decimal separator (point or comma), and be defined as the environment variable in the constructor
- [x] change `pi`, `omega`, `alfa`, etc. to &pi;, &omega;, &alpha;
- [x] change `deg` to ° 
- [x] fix the empty unit support; currently, it throws an error like:
```
ERROR (exercise fizyka/wskazowki-1): Error: INVALID UNIT FORMAT
    at Function.convertToLaTeX (equationExercise.ts:493:13)
    at equationExercise.ts:263:36
    at Array.forEach (<anonymous>)
    at new EquationExercise (equationExercise.ts:222:25)
    at Function.analyze (exercisesController.ts:32:18)
    at ExercisesController.getExercise (exercisesController.ts:51:46)
    at ExercisesController.buildExercise (exercisesController.ts:63:14)
    at ExercisesController._build (exercisesController.ts:83:18)
    at ExercisesController.buildSection (exercisesController.ts:76:22)
    at ExercisesController._build (exercisesController.ts:87:21)
```

**Comment by Nircek** [comment]
@Marwyk2003 I haven't seen any standard Random Number Generator. And even I can't find any nice-looking session library. So in my view, we should write RNG ourselves.

**Comment by Nircek** [comment]
@Marwyk2003, there is stuff to be done:
- [ ] add the short space between a value and a unit in LaTeX form
- [ ] add the possibility to redefine variable; currently, it throws an error like:
```
TypeError: this.variables[name].rand is not a function
    at EquationExercise.render (equationExercise.ts:331:53)
    at exercisesController.ts:162:36
    at Function.exists (exercisesController.ts:143:13)
    at exercisesController.ts:158:35
    at Function.predictDeath (exercisesController.ts:128:13)
    at ExercisesController.get (exercisesController.ts:156:31)
    at dispatch (middleware.ts:41:13)
    at seed (seedMiddleware.ts:14:9)
    at dispatch (middleware.ts:41:13)
    at router.ts:866:20
 ```
- [ ] ignore the spaces in the calculation part
- [ ] add a possibility to have `'` in a variable name and compile it nicely to LaTeX
- [ ] add the static property in EqEx specifies a decimal separator (point or comma), and be defined as the environment variable in the constructor
- [ ] change `pi`, `omega`, `alfa`, etc. to &pi;, &omega;, &alpha;
- [ ] fix the empty unit support; currently, it throws an error like:
```
ERROR (exercise fizyka/wskazowki-1): Error: INVALID UNIT FORMAT
    at Function.convertToLaTeX (equationExercise.ts:493:13)
    at equationExercise.ts:263:36
    at Array.forEach (<anonymous>)
    at new EquationExercise (equationExercise.ts:222:25)
    at Function.analyze (exercisesController.ts:32:18)
    at ExercisesController.getExercise (exercisesController.ts:51:46)
    at ExercisesController.buildExercise (exercisesController.ts:63:14)
    at ExercisesController._build (exercisesController.ts:83:18)
    at ExercisesController.buildSection (exercisesController.ts:76:22)
    at ExercisesController._build (exercisesController.ts:87:21)
```

**Comment by Marwyk2003** [comment]
The rest (3rd, 4th, 5th) will be featured in v0.2.

**Comment by Nircek** [comment]
@Marwyk2003 There is no `lambda` or `theta` parsing. And why didn't you make all greek letters?
